# Generated by Django 2.2.5 on 2021-01-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=240, verbose_name='任务清单')),
            ],
            options={
                'verbose_name': '任务',
                'db_table': 'tb_todo',
            },
        ),
    ]
